In [1]:
%matplotlib

Using matplotlib backend: Qt5Agg


In [2]:
import matplotlib as mpl

In [4]:
from matplotlib import pyplot as plt

In [8]:
img_path = 'photo_data/flower_photos/daisy'
import os
for i,img in enumerate(os.listdir(img_path)):
    img_file = os.path.join(img_path,img)
    img_read = plt.imread(img_file)
    plt.imshow(img_read)
    if i > 0:
        break
    i += 1

In [9]:
img_file

'photo_data/flower_photos/daisy/2511306240_9047015f2d_n.jpg'

In [10]:
import tensorflow as tf

/usr/bigdatas/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [11]:
img_raw = tf.gfile.FastGFile(img_file,'r').read()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [5]:
from numpy.random import rand

In [4]:
arr1=rand(10)

In [5]:
arr1.shape

(10,)

In [6]:
arr1

array([0.8285582 , 0.53069306, 0.68794202, 0.67319543, 0.86579063,
       0.55664269, 0.5365049 , 0.34008804, 0.90576975, 0.52667839])

In [7]:
arr2=rand(2,4)

In [8]:
arr2

array([[0.80713401, 0.23056378, 0.87889816, 0.05535886],
       [0.19131482, 0.55917698, 0.43012899, 0.54703342]])

In [9]:
import os

In [15]:
os.path.dirname(os.getcwd())

'/usr/project'

In [19]:
os.path.dirname(os.pardir)

''

In [20]:
    from numpy.random import rand
    x = rand(10)
    f = lambda a:a**2
    y = [f(i) for i in x]
    xlab = 'rand input'
    ylab = 'square out'
    title = 'test graph work or not'

In [2]:
from matplotlib import pyplot as plt

In [22]:
plt.title = title

In [23]:
plt.plot(x,y,'--o')

In [24]:
plt.xlabel = xlab

In [6]:
import time

In [8]:
    plt.ion()
    x = rand(100)
    for e in range(100):
        #plt.clf()
        #x = rand(10)
        #f = lambda a:a**2
        y = x[e]**2
        xlab = 'rand input'
        ylab = 'square out'
        title = 'test graph work or not'
    #fig = plt.figure(figsize=(14,10))
        plt.plot(x[e],y,'--o')
        plt.draw()
    #plt.show()
        #plot_figure(plt,x,y,xlab,ylab,title)
        #fig.savefig('figure/test.jpg')
        time.sleep(0.1)

In [3]:
from matplotlib.animation import FuncAnimation

In [1]:
#get_variable
import tensorflow as tf

with tf.variable_scope('test'):
    v=tf.get_variable('v',shape=[1],dtype=tf.float32,initializer=tf.truncated_normal_initializer(stddev=0.1))

/usr/bigdatas/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
for varible in tf.global_variables():
    print(varible.op.name)

test/v


In [6]:
#extract var directly
with tf.variable_scope('test',reuse=True):
    v1=tf.get_variable('v')
    print(v==v1)

True


In [6]:

ones=4*tf.ones([20,1])
init=tf.placeholder(dtype=tf.float32,shape=[20,10],name='input_seq')
with tf.variable_scope('mul',reuse=None):
    w=tf.get_variable('w_mul',shape=[20,10],dtype=tf.float32,initializer=tf.truncated_normal_initializer())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    conc=tf.concat([tf.cast(ones,tf.float32),w],axis=-1)
    ones_value=ones.eval()
    conc_value=sess.run(conc)
    print("ones_value:\n{}\nconc_value:\n{}".format(ones_value,conc_value))


ones_value:
[[4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]]
conc_value:
[[ 4.          0.45895004 -1.4648507   1.191948   -0.3786284   0.3606574
  -1.2090638   0.3623068   0.28405094  1.0035793   0.21691337]
 [ 4.          1.5347137  -0.78539056  0.5527898  -0.6771349   0.27365318
  -1.6803143  -1.2084278  -0.6875291  -0.5584032  -1.1136049 ]
 [ 4.         -0.47495234 -0.67257476  0.06991777 -0.48239243  0.21038298
  -1.4719658   1.047803    0.25456628  0.13270514  0.47941598]
 [ 4.          0.41206685 -1.7311575  -0.13746464 -0.18357672 -0.7823523
   0.7277283  -0.86665875 -0.18353648 -1.6817217  -1.0276768 ]
 [ 4.         -1.0339714   1.0520983   0.06216288 -0.0730743   1.4333575
  -0.4002534   0.2996399  -0.2378782  -0.25251588 -0.37252215]
 [ 4.         -0.54841244  0.45948315  0.47795305 -0.92701185 -1.5417539
  -1.7486894   1.8885005  -0.602428    1.6034775   1.1624408 ]
 [ 4.         -1.0043437  -0.16446896

In [11]:
fig,ax=plt.subplots()
#x=[];y=[]
ln, = ax.plot([],[],'k-',animated=False)
def init():
    ax.set_xlim(0,1)
    ax.set_ylim(0,1)
    plt.rcParams['axes.grid']=True
    plt.rcParams['axes.grid.axis']='y'
    plt.rcParams['grid.color']='grey'
    return ln,

def gen_data():
    for e in range(20):
        x = rand(10)
        y = x**2
        yield x,y

def update(data):
    #y.append(frame**2)
    ln.set_data(data[0],data[1])
    return ln,
an=FuncAnimation(fig,func=update,frames=gen_data,init_func=init,blit=True)
plt.show()

In [48]:
x=range(10);f=lambda x:x**2
y=[f(i) for i in x]
dot, = ax.plot(x,y,'r*')

In [51]:
plt.close()

In [1]:
import tensorflow as tf
from tensorflow.python.framework import graph_util

/usr/bigdatas/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
import os
#os.listdir()
if not os.path.exists('testSave'):
    os.mkdir('testSave')

In [2]:
v1=tf.Variable(tf.constant(1.0,shape=[1]),name='v1')
v2=tf.Variable(tf.constant(2.0,shape=[1]),name='v2')
result = v1 + v2
saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess,os.path.join('test','model.ckpt'))

NameError: name 'os' is not defined

In [8]:
os.listdir('test/')

['model.ckpt.index',
 'model.ckpt.meta',
 'checkpoint',
 'model.ckpt.data-00000-of-00001']

In [10]:
#export meta graph to json file
#saver.export_meta_graph('testSave/add.json',as_text=True)
ckpt=tf.train.get_checkpoint_state('test')
print(ckpt)
ckpt_path=ckpt.model_checkpoint_path
print(ckpt_path)

model_checkpoint_path: "test/model.ckpt"
all_model_checkpoint_paths: "test/model.ckpt"

test/model.ckpt


In [11]:
with open('test/checkpoint','r') as f:
    print("checkpoint content:",f.read())

checkpoint content: model_checkpoint_path: "model.ckpt"
all_model_checkpoint_paths: "model.ckpt"



In [13]:
#restore meta graph without redefine the variable and op
saver=tf.train.import_meta_graph('test/model.ckpt.meta')
with tf.Session() as sess:
    saver.restore(sess,'test/model.ckpt')
    result=tf.get_default_graph().get_tensor_by_name("add:0")
    print(sess.run(result))

INFO:tensorflow:Restoring parameters from test/model.ckpt
[3.]


In [15]:
v1=tf.Variable(tf.constant(1.0,shape=[1]),name='v11')
v2=tf.Variable(tf.constant(2.0,shape=[1]),name='v21')
result = v1 + v2
saver=tf.train.Saver({'v1':v1,'v2':v2})
with tf.Session() as sess:
    saver.restore(sess,'test/model.ckpt')
    print(sess.run(result))

INFO:tensorflow:Restoring parameters from test/model.ckpt
[3.]


In [17]:
#define graph save op 
for var in tf.global_variables():
    print("var:{} and var name={}".format(var,var.op.name))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    graph_def=tf.get_default_graph().as_graph_def()
    output_graph_def=graph_util.convert_variables_to_constants(sess,graph_def,['add'])
    with tf.gfile.GFile('test/output_graph_def.pb','wb') as fw:
        fw.write(output_graph_def.SerializeToString())
        

var:<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref> and var name=v1
var:<tf.Variable 'v2:0' shape=(1,) dtype=float32_ref> and var name=v2
var:<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref> and var name=v1
var:<tf.Variable 'v2:0' shape=(1,) dtype=float32_ref> and var name=v2
var:<tf.Variable 'v1:0' shape=(1,) dtype=float32_ref> and var name=v1
var:<tf.Variable 'v2:0' shape=(1,) dtype=float32_ref> and var name=v2
var:<tf.Variable 'v1_3:0' shape=(1,) dtype=float32_ref> and var name=v1_3
var:<tf.Variable 'v2_3:0' shape=(1,) dtype=float32_ref> and var name=v2_3
var:<tf.Variable 'v11:0' shape=(1,) dtype=float32_ref> and var name=v11
var:<tf.Variable 'v21:0' shape=(1,) dtype=float32_ref> and var name=v21
INFO:tensorflow:Froze 2 variables.
INFO:tensorflow:Converted 2 variables to const ops.


In [19]:
from tensorflow.python.platform import gfile
with tf.Session() as sess:
    with gfile.FastGFile('test/output_graph_def.pb','rb') as fr:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(fr.read())
    #retore add op into current graph
    result = tf.import_graph_def(graph_def,return_elements=['add:0'])
    print(sess.run(result))
    
    

[array([3.], dtype=float32)]


In [6]:
v1=tf.Variable(tf.constant(0.1,shape=[1]),name='v11')
ema=tf.train.ExponentialMovingAverage(0.5)
move_average_op=ema.apply([v1])
for variable in tf.global_variables():
    print("var is:",variable)

var is: <tf.Variable 'v1:0' shape=(1,) dtype=float32_ref>
var is: <tf.Variable 'v2:0' shape=(1,) dtype=float32_ref>
var is: <tf.Variable 'v1_1:0' shape=(1,) dtype=float32_ref>
var is: <tf.Variable 'v1_1/ExponentialMovingAverage:0' shape=(1,) dtype=float32_ref>
var is: <tf.Variable 'v11:0' shape=(1,) dtype=float32_ref>
var is: <tf.Variable 'v11/ExponentialMovingAverage:0' shape=(1,) dtype=float32_ref>


In [7]:
saver=tf.train.Saver()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    tf.assign(v1,[10.0])
    sess.run(move_average_op)
    saver.save(sess,'test/model.ckpt')
    sess.run([v1,ema.average(v1)])
    

In [13]:
v1=tf.Variable(tf.constant(10.0,shape=[1]),name='v11')
ema=tf.train.ExponentialMovingAverage(0.9)
saver=tf.train.Saver(ema.variables_to_restore())
with tf.Session() as sess:
    saver.restore(sess,'test/model.ckpt')
    print(sess.run(v))

INFO:tensorflow:Restoring parameters from test/model.ckpt


NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key v/ExponentialMovingAverage not found in checkpoint
	 [[Node: save_9/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_9/Const_0_0, save_9/RestoreV2/tensor_names, save_9/RestoreV2/shape_and_slices)]]

Caused by op 'save_9/RestoreV2', defined at:
  File "/usr/bigdatas/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/bigdatas/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-3956ed2fd29e>", line 3, in <module>
    saver=tf.train.Saver(ema.variables_to_restore())
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/bigdatas/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key v/ExponentialMovingAverage not found in checkpoint
	 [[Node: save_9/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_9/Const_0_0, save_9/RestoreV2/tensor_names, save_9/RestoreV2/shape_and_slices)]]


In [8]:
for var in tf.global_variables():
    print(var)

<tf.Variable 'v11:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'v11_1:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'v11_2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'v11_3:0' shape=(1,) dtype=float32_ref>


In [2]:
import numpy as np
v1=tf.Variable([[1,2,3],[2,3,4]],name='v11')

In [9]:
v2=tf.placeholder(dtype=tf.float32,shape=[10,8],name='v2')
print("shape of v2:",tf.shape(v2))
print("shape of v2 1 dimension:",tf.shape(v2)[0])
print("shape get from v2:",v2.get_shape())
print("shape get from v2 1 dimension:",v2.get_shape()[0])
print("shape list from v2:",v2.get_shape().as_list())


shape of v2: Tensor("Shape_1:0", shape=(2,), dtype=int32)
shape of v2 1 dimension: Tensor("strided_slice_2:0", shape=(), dtype=int32)
shape get from v2: (10, 8)
shape get from v2 1 dimension: 10
shape list from v2: [10, 8]


In [3]:
shape=tf.shape(v1)

In [4]:
shape

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [5]:
shape[0]

<tf.Tensor 'strided_slice:0' shape=() dtype=int32>

In [6]:
shape[1]

<tf.Tensor 'strided_slice_1:0' shape=() dtype=int32>

In [11]:
v1.get_shape()[0] + 1

Dimension(3)

In [12]:
drop=tf.nn.dropout(v2,keep_prob=0.5)

In [13]:
drop.get_shape()

TensorShape([Dimension(10), Dimension(8)])

In [2]:
import numpy as np
arr=np.array(range(10))
arr.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
import tensorflow as tf
var=tf.Variable(arr)

In [4]:
var.get_shape().as_list()

[10]

In [5]:
var_re=tf.reshape(var,[2,5])


In [7]:
p=tf.placeholder(dtype=tf.float32,shape=[None,40,10,5])
shape_p=p.get_shape().as_list()
p_rs=tf.reshape(p,[-1,shape_p[1]*shape_p[2]*shape_p[3]])

In [8]:
p_rs.get_shape()

TensorShape([Dimension(None), Dimension(2000)])

In [10]:
from tensorflow.examples.tutorials.mnist import input_data

In [11]:
data_path='/usr/project/tensorflow_learn/data'
mnist_data=input_data.read_data_sets(data_path,one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /usr/project/tensorflow_learn/data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /usr/project/tensorflow_learn/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting /usr/project/tensorflow_learn/data/t10k-images-idx3-ubyte.gz
Extracting /usr/project/tensorflow_learn/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [12]:
type(mnist_data.test.images)

numpy.ndarray

In [13]:
mnist_data.test.images.shape

(10000, 784)

In [14]:
new_test=mnist_data.test.images.reshape([10000,28,28,1])